[package]
org = "xlibb"
name = "student_application_form_filling"
version = "0.1.0"
distribution = "2201.10.2"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "dharshi"
name = "selenium"
version = "0.1.0"
repository = "local"