[package]
distribution = "2201.10.0"
org = "xlibb"
name = "selenium"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = [] # TODO: Add keywords
# icon = "icon.png" # TODO: Add icon
repository = "https://github.com/xlibb/module-selenium"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
